name: hawahawa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  
  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/

  fonts:
    - family: BoldPixels
      fonts:
        - asset: assets/fonts/BoldPixels.ttf